-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM
(SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A INNER JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY (A.DATETIME - B.DATETIME) DESC)
WHERE rownum <= 2;