-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR
     , EXTRACT(MONTH FROM SALES_DATE) AS MONTH
     , COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT UI.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') AND TO_DATE('2021-12-31', 'YYYY-MM-DD')), 1) AS PUCHASED_RATIO
FROM USER_INFO UI LEFT OUTER JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE JOINED BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') AND TO_DATE('2021-12-31', 'YYYY-MM-DD')
AND OS.USER_ID IS NOT NULL 
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY EXTRACT(YEAR FROM SALES_DATE) ASC, EXTRACT(MONTH FROM SALES_DATE) ASC;