-- 코드를 입력하세요
SELECT TITLE, UGB.BOARD_ID, REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, TO_CHAR(UGR.CREATED_DATE, 'YYYY-MM-DD')
FROM USED_GOODS_BOARD UGB INNER JOIN USED_GOODS_REPLY UGR
ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
ORDER BY UGR.CREATED_DATE ASC, TITLE ASC;